using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.SceneManagement;
using TMPro;

public class GameMode : MonoBehaviour
{
    [SerializeField] private LevelScriptable levelScriptable;
    [SerializeField] private GameObject ballGO;
    [SerializeField] private Transform cup;
    [SerializeField] private BallCollecter ballCollecter;
    [SerializeField] private BallDestroyer ballDestroyer;
    [SerializeField] private GameObject gameOverUI;
    [SerializeField] private GameObject winConditionUI;
    [SerializeField] private TextMeshPro scoreText;
    [SerializeField] private Tube autoGeneratedTube;
    private Level level;
    private int ballCount;
    private int inCupBallCount;
    private int destroyedBallCount;
    private Tube tube;

    public void OnBallDestroy(int destroyedBallCount)
    {
        this.destroyedBallCount = destroyedBallCount;
        checkIsGameOver();
    }


    public void OnBallCollected(int collectedBallCount)
    {
        inCupBallCount = collectedBallCount;
        scoreText.text = $"{inCupBallCount}/{level.targetBallCount}";
        checkIsGameOver();
    }

    private void checkIsGameOver()
    {
        if (inCupBallCount >= level.targetBallCount)
            winConditionUI.SetActive(true);
        if (level.ballCount - destroyedBallCount < level.targetBallCount)
        {
            gameOverUI.SetActive(true);
        }
    }

    private void Start()
    {
        loadRandomLevel();
    }

    public void restartLevel()
    {
        SceneManager.LoadScene(SceneManager.GetActiveScene().buildIndex);
    }

    public void loadRandomLevel()
    {
        int randomIndex = Random.Range(0, levelScriptable.levels.Length);
        level = levelScriptable.levels[randomIndex];
        this.ballCount = level.ballCount;
        GameObject tubeGO = null;
        if (!level.autoGeneratedTube)
        {
            tubeGO = Instantiate(level.tubeGO);
            tube = tubeGO.GetComponent<Tube>();
        }
        else
        {
            tube = autoGeneratedTube;
            tube.transform.position += level.offsetCenter;
            tube.gameObject.SetActive(true);
            tube.GetComponent<TubeGenerator>().generateTube(level.svgFileName);
        }
        tube.generateBalls(ballCount, ballGO);
        tube.setTargetCup(cup);
        scoreText.text = $"0/{level.targetBallCount}";
    }
}
