using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine;


[CreateAssetMenu(fileName = "Level", menuName = "Level", order = 2)]
public class LevelScriptable : ScriptableObject
{
    [Header("Levels")]
    public Level[] levels;
}

[Serializable]
public class Level
{
    [Range(20,100)]public int ballCount;
    public GameObject tubeGO;
    [Range(20,100)] public int targetBallCount;
    public bool autoGeneratedTube;
    public string svgFileName;
    public Vector3 offsetCenter;
}
